### ISSUE TITLE
Saving settings does not keep the comments

### ISSUE THREAD

**Issue by taniman** [taniman/pt-beta-issues#1]
**Describe the bug**
Saving settings does not keep the comments

**To Reproduce**
1. Go to config in advanced mode
2. Click on DCA or PAIRS config
3. Add some comments and empty lines
4. Save
5. Switch to another window and comeback
6. comments are gone

**Expected behavior**
Comments should be kept

**Comment by djcrypto75** [comment]
fixed in last build
