### ISSUE TITLE
Error whilst refreshing on PT Monitor with Binance on a fresh install

### ISSUE THREAD

**Issue by mehtadone** [taniman/pt-beta-issues#12]
**Describe the bug**
Fresh 2.1 Beta 24 install. Using existing application.properties and a fresh copy of Battens settings. PT Monitor does not load. On Binance

**To Reproduce**
1.  Install 2.1 Beta 24 using existing application.properties
2. Open PT Monitoring page

**Expected behavior**
Monitoring page should load

**Screenshots**
![image](https://user-images.githubusercontent.com/8123496/42287322-cc9d489a-7fad-11e8-95f2-f799701fe433.png)

![image](https://user-images.githubusercontent.com/8123496/42287223-74c8fe8e-7fad-11e8-9cd2-c4d7898aadf3.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome

**Additional context**
Logs attached
[ProfitTrailer.log](https://github.com/taniman/pt-beta-issues/files/2163824/ProfitTrailer.log)

Error in Chrome console: 

```
Mixed Content: The page at '<URL>' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint '<URL>'. This request has been blocked; the content must be served over HTTPS.
```

and

```
Mixed Content: The page at 'https://xxxxxxxx/monitoring' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://xxxxxxx/monitoring/data?_=1530721635348'. This request has been blocked; the content must be served over HTTPS.
```

**Comment by taniman** [comment]
Check demo.profittrailer.com or io.
HTTPS request are done and working properly. I suspect some setup thing...

**Comment by mehtadone** [comment]
It's all setup using Helmi's guide. I'll go through to see what maybe missing https://gist.github.com/Helmi/68879e72d2221ef0be24fcd6776c0c97
