### ISSUE TITLE
BNB price lost

### ISSUE THREAD

**Issue by t1m3c** [taniman/pt-beta-issues#19]
Please check BNB specially.
Log: https://cdn.discordapp.com/attachments/406923371515871233/466088994199830529/new_1.txt

Settings: 
BNB_initial_cost = 0.002
BNB_A_buy_strategy = RSI
BNB_A_buy_value = 100
BNB_A_buy_value_limit = 0
BNB_trailing_buy = 0
BNB_B_buy_strategy = DISABLED
BNB_C_buy_strategy = DISABLED
BNB_D_buy_strategy = DISABLED
BNB_E_buy_strategy = DISABLED
BNB_A_sell_strategy = GAIN
BNB_A_sell_value = 100
BNB_DCA_enabled = false
BNB_pending_order_wait_time = 0
BNB_take_profit_percentage = 100
BNB_rebuy_timeout = 0

**Comment by taniman** [comment]
If you use BNB to pay for fees you can trade  with BNB.
