### ISSUE TITLE
I cannot load a profile b34

### ISSUE THREAD

**Issue by dialup4eg** [taniman/pt-beta-issues#21]
**Describe the bug**
I cannot load a profile.

**To Reproduce**
1. Go to 'saved'
2. Click on 'default'(my btc profile)

**Expected behavior**
After installing beta 34, a window appears with a selection. I choose saved profiles. Choose your BTC profile I called it default. After that I get what is in the picture. After restarting the bot, again asked to select a profile.

**Screenshots**
![image](https://user-images.githubusercontent.com/34375614/43016515-841dc5ba-8c6c-11e8-9fe4-3db0eb7e8c6a.png)

**Desktop (please complete the following information):**
 - chrome 67

**Additional context**

**Comment by taniman** [comment]
You should provide your log file.  Also who is this on discord?
