### ISSUE TITLE
PT 2.1.0 B38 is showing bigger profit than it really is on Poloniex, Bittrex, Binance

### ISSUE THREAD

**Issue by arthurengeletrica** [taniman/pt-beta-issues#23]
PT version is 2.1.0 B38
3 Bots : Poloniex, Bittrex, Binance
OS of it's VPS is Ubuntu 16.04
VPS is Contabo

**Describe the bug**
PT is showing bigger profit than it really is on Poloniex, Bittrex, Binance, it even tries to sell with a loss because of that without knowing what it is doing

The Bot, for Poloniex is considering 0.2% total fees (maker + taker) for poloniex, it should consider 0.3%
At Bittrex it is considering about 0.2% total fees, it should consider 0.5%
At Binance it is considering 0.05% total fees, it should consider 0.1%

**To Reproduce**
1. Use 2.1.0 B38 with Poloniex, Bittrex and Binance
2. Wait for it to sell something for positive profit
3. After it sells, calculate profit based on exchanges' fees and raw profit

**Expected behavior**
Poloniex should show 0.28% profit on last trade, it shows 0.38%
Bittrex should show -0.10 profit on last trade and not try to sell at this loss ratio, and it showed +0.10%
Binance should show about 0.21% profit on last trade it shows 0.26%

**Screenshots**
Last trade at Poloniex:

![image](https://user-images.githubusercontent.com/38858258/43371500-b4508192-9369-11e8-9731-dfb1e635cd5b.png)

Last trade at Bittrex:

![image](https://user-images.githubusercontent.com/38858258/43371502-bb101aa6-9369-11e8-9204-9bb34483c3cf.png)

Last trade at Binance:

![image](https://user-images.githubusercontent.com/38858258/43371504-bff8b5b4-9369-11e8-9077-08466e7b1a39.png)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [Chrome]
 - Version [ 67.0.3396.99  64 bits]

LOG FILES:

Poloniex

[ProfitTrailer.log](https://github.com/taniman/pt-beta-issues/files/2239262/ProfitTrailer.log)

Bittrex

[ProfitTrailer.log](https://github.com/taniman/pt-beta-issues/files/2239263/ProfitTrailer.log)

Binance

[ProfitTrailer.log](https://github.com/taniman/pt-beta-issues/files/2239264/ProfitTrailer.log)

** SETTINGS **

Poloniex:

[Mercado_Bull_Scalpinho-DCA (1).txt](https://github.com/taniman/pt-beta-issues/files/2239272/Mercado_Bull_Scalpinho-DCA.1.txt)
[Mercado_Bull_Scalpinho-INDICATORS (1).txt](https://github.com/taniman/pt-beta-issues/files/2239273/Mercado_Bull_Scalpinho-INDICATORS.1.txt)
[Mercado_Bull_Scalpinho-PAIRS (1).txt](https://github.com/taniman/pt-beta-issues/files/2239274/Mercado_Bull_Scalpinho-PAIRS.1.txt)

Bittrex

[Mercado_Bull_Scalpinho-PAIRS (1).txt](https://github.com/taniman/pt-beta-issues/files/2239275/Mercado_Bull_Scalpinho-PAIRS.1.txt)
[Mercado_Bull_Scalpinho-DCA (1).txt](https://github.com/taniman/pt-beta-issues/files/2239276/Mercado_Bull_Scalpinho-DCA.1.txt)
[Mercado_Bull_Scalpinho-INDICATORS (1).txt](https://github.com/taniman/pt-beta-issues/files/2239277/Mercado_Bull_Scalpinho-INDICATORS.1.txt)

Binance

[Mercado_bull_Scalpinho-INDICATORS (1).txt](https://github.com/taniman/pt-beta-issues/files/2239278/Mercado_bull_Scalpinho-INDICATORS.1.txt)
[Mercado_bull_Scalpinho-PAIRS (1).txt](https://github.com/taniman/pt-beta-issues/files/2239279/Mercado_bull_Scalpinho-PAIRS.1.txt)
[Mercado_bull_Scalpinho-DCA (1).txt](https://github.com/taniman/pt-beta-issues/files/2239280/Mercado_bull_Scalpinho-DCA.1.txt)

**Comment by taniman** [comment]
Found the problem. It's not a fee's issue. You are using orderbook profit calculation. And there is a bug in the display. of the profit. 

I could only verify this for your Poloniex and Binance account. 
You have many errors and messages in your log files.

Please check and fix your PTTracker. If you are using the latest beta version it requires you to setup an api_token
