### ISSUE TITLE
Consecutive buy/sell not triggered correctly on B39

### ISSUE THREAD

**Issue by t1m3c** [taniman/pt-beta-issues#24]
SOM triggered by consecutive buy, but not triggered back on sell, Consecutive buy/sell settings is 6/4
https://gyazo.com/77c8c272d27412f71ea8621459ccb404

**Comment by taniman** [comment]
please provide your profittrailerdata.json

**Comment by t1m3c** [comment]
[ProfitTrailerData.json.txt](https://github.com/taniman/pt-beta-issues/files/2249016/ProfitTrailerData.json.txt)

**Comment by taniman** [comment]
sorry also your log file.

**Comment by taniman** [comment]
I am not finding any sells in your PRofittrailerData.json

**Comment by taniman** [comment]
![image](https://user-images.githubusercontent.com/6751341/43520419-1b7618c0-9593-11e8-9322-ce20ac50ecab.png)

Also I am seeing buys in your file. So how did you manage to get these buys in?

**Comment by t1m3c** [comment]
Here we are. [ProfitTrailer.log](https://github.com/taniman/pt-beta-issues/files/2249335/ProfitTrailer.log)

**Comment by taniman** [comment]
You have DCA ignore sell only mode enabled right?

**Comment by taniman** [comment]
I do not understand how the bot started buying if you say SOM was not disabled...

**Comment by taniman** [comment]
The way I see it. It just reenabled.. after those new 6 buys?

**Comment by t1m3c** [comment]
Yes, i reenabled it with somo.
